version: '3.9'
name: documents-clustering
services:
  app:
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "8000:8000"
    networks:
      - net

volumes:
    index_data:
      driver: local
    backups:
      driver: local

networks:
    net:
      driver: bridge
