version: '3.9'

services:
  web:
    build:
      context: ../
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    environment:
      FLASK_ENV: development

  application:
    build:
      context: .
      dockerfile: ../Dockerfile
    image: application
    container_name: application
    volumes:
      - ../:/app/
    networks:
      - net

  chroma:
      image: ghcr.io/chroma-core/chroma:latest
      volumes:
        - index_data:/chroma/.chroma/index
      ports:
        - "8000:8000"
      networks:
        - net

volumes:
  index_data:
      driver: local
  backups:
      driver: local

networks:
  net:
    driver: bridge